import { REPO_URL } from '../../config/env'

type Props = {
  /** Attribution for the current episode's audio, if any. */
  credit: string | null
}

/** Thin banner explaining that the public site plays pre-processed episodes. */
export function DemoBanner({ credit }: Props) {
  return (
    <div className="demo-banner" role="note">
      <span className="demo-banner__badge">Live demo</span>
      <span className="demo-banner__text">
        Pre-processed episodes: transcript, entities, timeline and answers were generated by PodLens ahead of time.
        Run it locally to analyse your own audio.
      </span>
      {credit ? <span className="demo-banner__credit">{credit}</span> : null}
      <a className="demo-banner__link" href={REPO_URL} target="_blank" rel="noreferrer">
        View on GitHub
      </a>
    </div>
  )
}
